# app.py
"""Fast snapshot dashboard for the Indian screener.

Loads pre-built Nifty 50 / Nifty 500 snapshots generated by update_data.py.
"""

import json
from datetime import datetime
from pathlib import Path

import altair as alt
import numpy as np
import pandas as pd
import streamlit as st

from screener_app_legacy import render_reference_guide


# ═══════════════════════════════════════════════════════════════════════════════
# Constants / helpers (mirrors the S&P 500 dashboard look & feel)
# ═══════════════════════════════════════════════════════════════════════════════
SLOAN_ACCRUALS_THRESHOLD = 0.08

ROE_PRIMARY_SECTORS = {"Financials"}

QUALITY_THRESHOLDS = {
    "roic_min": 8.0,
    "int_coverage_min": 3.0,
    "op_margin_min": 5.0,
}

SECTOR_QUALITY_THRESHOLDS = {
    "Information Technology": {"roic_min": 12.0, "int_coverage_min": 5.0, "op_margin_min": 15.0},
    "Communication Services": {"roic_min":  8.0, "int_coverage_min": 3.0, "op_margin_min": 12.0},
    "Consumer Discretionary": {"roic_min":  8.0, "int_coverage_min": 3.0, "op_margin_min":  8.0},
    "Consumer Staples":       {"roic_min":  8.0, "int_coverage_min": 4.0, "op_margin_min":  6.0},
    "Energy":                 {"roic_min":  6.0, "int_coverage_min": 3.0, "op_margin_min": 10.0},
    "Oil, Gas & Consumable Fuels": {"roic_min": 6.0, "int_coverage_min": 3.0, "op_margin_min": 10.0},
    "Financials":             {"roic_min":  8.0, "int_coverage_min": 3.0, "op_margin_min": 15.0},
    "Health Care":            {"roic_min": 10.0, "int_coverage_min": 5.0, "op_margin_min": 12.0},
    "Industrials":            {"roic_min":  9.0, "int_coverage_min": 4.0, "op_margin_min":  8.0},
    "Materials":              {"roic_min":  7.0, "int_coverage_min": 3.0, "op_margin_min":  8.0},
    "Real Estate":            {"roic_min":  5.0, "int_coverage_min": 2.0, "op_margin_min": 25.0},
    "Utilities":              {"roic_min":  4.0, "int_coverage_min": 2.0, "op_margin_min": 12.0},
}

SECTOR_FACTOR_WEIGHTS = {
    "Information Technology": {
        "valuation": 0.20, "quality": 0.25, "peg": 0.25,
        "earn_traj": 0.15, "momentum": 0.15,
    },
    "Consumer Discretionary": {
        "valuation": 0.20, "quality": 0.20, "peg": 0.22,
        "earn_traj": 0.18, "momentum": 0.20,
    },
    "Communication Services": {
        "valuation": 0.22, "quality": 0.23, "peg": 0.22,
        "earn_traj": 0.18, "momentum": 0.15,
    },
    "Health Care": {
        "valuation": 0.25, "quality": 0.30, "peg": 0.18,
        "earn_traj": 0.15, "momentum": 0.12,
    },
    "Industrials": {
        "valuation": 0.25, "quality": 0.28, "peg": 0.18,
        "earn_traj": 0.17, "momentum": 0.12,
    },
    "Consumer Staples": {
        "valuation": 0.28, "quality": 0.32, "peg": 0.10,
        "earn_traj": 0.15, "momentum": 0.15,
    },
    "Financials": {
        "valuation": 0.30, "quality": 0.25, "peg": 0.18,
        "earn_traj": 0.17, "momentum": 0.10,
    },
    "Energy": {
        "valuation": 0.30, "quality": 0.18, "peg": 0.12,
        "earn_traj": 0.15, "momentum": 0.25,
    },
    "Oil, Gas & Consumable Fuels": {
        "valuation": 0.30, "quality": 0.18, "peg": 0.12,
        "earn_traj": 0.15, "momentum": 0.25,
    },
    "Materials": {
        "valuation": 0.28, "quality": 0.20, "peg": 0.12,
        "earn_traj": 0.15, "momentum": 0.25,
    },
    "Real Estate": {
        "valuation": 0.30, "quality": 0.18, "peg": 0.10,
        "earn_traj": 0.22, "momentum": 0.20,
    },
    "Utilities": {
        "valuation": 0.38, "quality": 0.27, "peg": 0.05,
        "earn_traj": 0.15, "momentum": 0.15,
    },
}

DEFAULT_FACTOR_WEIGHTS = {
    "valuation": 0.25, "quality": 0.25, "peg": 0.20,
    "earn_traj": 0.15, "momentum": 0.15,
}

METRIC_DIRECTION = {
    "Score": "green",
    "Overall Score": "green",
    "Quality Score": "green",
    "Momentum Score": "red",
}


def safe_round(series: pd.Series, decimals=2) -> pd.Series:
    return pd.to_numeric(series, errors="coerce").round(decimals)


def _hex_to_rgb(hex_color: str):
    hex_color = hex_color.lstrip("#")
    return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))


def _blend_color(ratio: float, low_hex: str, high_hex: str) -> str:
    low = _hex_to_rgb(low_hex)
    high = _hex_to_rgb(high_hex)
    rgb = tuple(int(low[i] + (high[i] - low[i]) * ratio) for i in range(3))
    return f"background-color: rgb({rgb[0]},{rgb[1]},{rgb[2]}); color: #1f2937;"


def _column_gradient(series: pd.Series, low_hex: str, high_hex: str) -> list:
    s = pd.to_numeric(series, errors="coerce")
    s_min, s_max = s.min(), s.max()
    if pd.isna(s_min) or pd.isna(s_max) or s_max == s_min:
        return [""] * len(s)
    ratios = ((s - s_min) / (s_max - s_min)).tolist()
    return [_blend_color(r, low_hex, high_hex) if pd.notna(r) else "" for r in ratios]


def _green_grad(s: pd.Series) -> list:
    return _column_gradient(s, "#d4f7d4", "#6bc46b")


def _red_grad(s: pd.Series) -> list:
    return _column_gradient(s, "#ffd9d9", "#e07a7a")


def _sector_quality_thresholds(sector):
    return SECTOR_QUALITY_THRESHOLDS.get(sector, QUALITY_THRESHOLDS)


def quality_flag(roic, roe, ic, om, sloan_ratio=None, sector=None):
    EPSILON = 1e-9
    flags = []
    th = _sector_quality_thresholds(sector)
    prof = (roe if sector in ROE_PRIMARY_SECTORS
            else (roic if (roic is not None and not pd.isna(roic)) else roe))
    lbl = ("ROE" if sector in ROE_PRIMARY_SECTORS
           else ("ROIC" if (roic is not None and not pd.isna(roic)) else "ROE"))
    roic_min = th["roic_min"]
    if prof is not None and not pd.isna(prof) and float(prof) < roic_min - EPSILON:
        flags.append("{}<{:.0f}%".format(lbl, roic_min))
    if ic is not None and not pd.isna(ic) and float(ic) < th["int_coverage_min"]:
        flags.append("IntCov<{:.0f}x".format(th["int_coverage_min"]))
    if sector not in ROE_PRIMARY_SECTORS:
        if om is not None and not pd.isna(om) and float(om) < th["op_margin_min"]:
            flags.append("Margin<{:.0f}%".format(th["op_margin_min"]))
    if sloan_ratio is not None and not pd.isna(sloan_ratio) and float(sloan_ratio) > SLOAN_ACCRUALS_THRESHOLD:
        flags.append("HighAccruals")
    return ", ".join(flags) if flags else "Pass"


# ═══════════════════════════════════════════════════════════════════════════════
# Data loading
# ═══════════════════════════════════════════════════════════════════════════════
DATA_DIR = Path(__file__).parent / "data"


@st.cache_data(ttl=300)
def _load_snapshot(name: str) -> pd.DataFrame:
    path = DATA_DIR / name
    if not path.exists():
        return pd.DataFrame()
    df = pd.read_parquet(path)
    for col in df.columns:
        if df[col].dtype.name == "object":
            df[col] = df[col].infer_objects()
    return df


def _latest_update_text() -> str:
    path = DATA_DIR / "last_update.json"
    if not path.exists():
        return "unknown"
    try:
        dt = datetime.fromisoformat(path.read_text().strip())
        return dt.strftime("%Y-%m-%d %H:%M UTC")
    except Exception:
        return "unknown"


# ═══════════════════════════════════════════════════════════════════════════════
# Shared screener page renderer
# ═══════════════════════════════════════════════════════════════════════════════
def _render_screener_page(scr: pd.DataFrame, title: str, csv_prefix: str):
    if scr.empty:
        st.warning(f"{title} snapshot is not available yet.")
        return

    st.markdown(f"### {title}")

    # ── Sidebar filters ────────────────────────────────────────────────────────
    key_prefix = csv_prefix.replace("_screener", "")
    all_sectors = sorted(scr["Sector"].dropna().unique().tolist())
    with st.sidebar:
        st.markdown(f"### {title} Filters")
        sector_sel = st.selectbox(
            "Sector", ["All Sectors"] + all_sectors,
            key=f"{key_prefix}_sector",
        )
        sort_by = st.selectbox(
            "Sort by", [
                "Sector then Rank", "Overall Score high to low", "Score high to low",
                "Conviction high to low", "MC% of Index high to low",
                "Price low to high", "Price high to low", "Mkt Cap high to low",
                "PE low to high", "Fwd PE low to high", "PEG low to high",
                "Quality Score high", "ROIC high to low", "ROE high to low",
                "Earn Traj high to low", "Rev Growth high to low",
                "Momentum Score high", "52W Pos low to high",
                "P/E vs Sector Med low to high",
            ],
            key=f"{key_prefix}_sort",
        )
        mc_min_l = st.number_input(
            "Min Mkt Cap (LCr)", value=0, step=10, min_value=0,
            key=f"{key_prefix}_mc_min",
        )
        pe_max = st.number_input(
            "Max P/E", value=9999, step=50, min_value=0,
            key=f"{key_prefix}_pe_max",
        )
        qual_min_f = st.number_input(
            "Min Quality Score", value=0.0, step=5.0,
            min_value=0.0, max_value=100.0,
            key=f"{key_prefix}_qual_min",
        )

    # ── Apply filters & sort ─────────────────────────────────────────────────
    filt = scr.copy()
    if sector_sel != "All Sectors":
        filt = filt[filt["Sector"] == sector_sel]
    filt = filt[(filt["Mkt Cap (LCr)"].isna()) | (filt["Mkt Cap (LCr)"] >= mc_min_l)]
    filt = filt[(filt["P/E"].isna()) | (filt["P/E"] <= pe_max)]
    filt = filt[(filt["Quality Score"].isna()) | (filt["Quality Score"] >= qual_min_f)]

    sort_map = {
        "Sector then Rank": (["Sector", "Rank"], [True, True]),
        "Overall Score high to low": (["Score"], [False]),
        "Score high to low": (["Score"], [False]),
        "Conviction high to low": (["Conviction Score"], [False]),
        "MC% of Index high to low": (["MC% of Index"], [False]),
        "Price low to high": (["Price (Rs)"], [True]),
        "Price high to low": (["Price (Rs)"], [False]),
        "Mkt Cap high to low": (["Mkt Cap (LCr)"], [False]),
        "PE low to high": (["P/E"], [True]),
        "Fwd PE low to high": (["Fwd P/E"], [True]),
        "PEG low to high": (["PEG"], [True]),
        "Quality Score high": (["Quality Score"], [False]),
        "ROIC high to low": (["ROIC%"], [False]),
        "ROE high to low": (["ROE%"], [False]),
        "Earn Traj high to low": (["Earn Traj"], [False]),
        "Rev Growth high to low": (["Rev Growth% (CAGR)"], [False]),
        "Momentum Score high": (["Momentum Score"], [False]),
        "52W Pos low to high": (["52W Pos%"], [True]),
        "P/E vs Sector Med low to high": (["P/E vs Sector Med"], [True]),
    }
    sc, sa = sort_map.get(sort_by, (["Sector", "Rank"], [True, True]))
    # Only sort by columns that exist
    sc = [c for c in sc if c in filt.columns]
    if sc:
        filt = filt.sort_values(sc, ascending=sa[: len(sc)], na_position="last")

    # ── Summary cards ────────────────────────────────────────────────────────
    if not filt.empty:
        m1, m2, m3, m4, m5 = st.columns(5)
        m1.metric("Passing stocks", len(filt))
        m2.metric("Avg Quality", f"{filt['Quality Score'].mean():.2f}")
        m3.metric("Avg Momentum", f"{filt['Momentum Score'].mean():.2f}")
        m4.metric("Avg Score", f"{filt['Score'].mean():.2f}")
        best_sector = (filt.groupby("Sector")["Score"].mean().idxmax()
                       if "Sector" in filt.columns else "—")
        m5.metric("Best sector", best_sector)
    else:
        st.warning("No stocks match the current filters.")

    st.caption("Showing **{}** of **{}** · Sector: {} · Sort: {}".format(
        len(filt), len(scr), sector_sel, sort_by))

    # ── Build display table ──────────────────────────────────────────────────
    disp = filt.copy()
    disp["Price (Rs)"] = safe_round(disp["Price (Rs)"], 2)
    disp["Mkt Cap (LCr)"] = safe_round(disp["Mkt Cap (LCr)"], 2)
    disp["MC% of Index"] = safe_round(disp["MC% of Index"], 2)

    if "P/E" in disp.columns and "Sector" in disp.columns:
        sector_pe_med = disp.groupby("Sector")["P/E"].transform("median")
        disp["P/E vs Sector Med"] = safe_round(disp["P/E"] / sector_pe_med.replace(0, np.nan), 2)

    disp["Quality Flag"] = disp.apply(
        lambda r: quality_flag(
            r.get("ROIC%"), r.get("ROE%"), r.get("Int Coverage"),
            r.get("Op Margin%"), sector=r.get("Sector"),
        ), axis=1,
    )

    disp["Overall Score"] = safe_round(disp["Score"], 2)

    ROUND_COLS = [
        "P/E", "Fwd P/E", "PEG", "Earn Traj", "52W Pos%",
        "ROIC%", "ROE%", "Int Coverage", "Op Margin%", "Debt/Eq",
        "Quality Score", "Momentum Score", "Overall Score",
        "Ret 1Mo%", "Ret 3Mo%", "Ret 6Mo%", "Trailing Vol%",
        "Score", "Conviction Score", "MC% of Index",
        "Rev Growth% (CAGR)", "P/E vs Sector Med",
        "Rev Q1 (1000Cr)", "Rev Q2 (1000Cr)", "Rev Q3 (1000Cr)", "Rev Q4 (1000Cr)",
    ]
    for c in ROUND_COLS:
        if c in disp.columns:
            disp[c] = safe_round(disp[c], 2)

    if "Rank" in disp.columns:
        disp["Rank"] = pd.to_numeric(disp["Rank"], errors="coerce").apply(
            lambda v: int(v) if pd.notna(v) else pd.NA)

    COLS = [
        "Ticker", "Sector", "Price (Rs)", "Mkt Cap (LCr)", "MC% of Index",
        "Overall Score", "P/E", "P/E vs Sector Med", "Fwd P/E",
        "PEG", "PEG Method", "Earn Traj",
        "ROIC%", "ROE%", "Int Coverage", "Op Margin%", "Debt/Eq",
        "Quality Score", "Quality Flag",
        "Momentum Score",
        "Ret 1Mo%", "Ret 3Mo%", "Ret 6Mo%", "Trailing Vol%",
        "52W Pos%", "Score", "Rank", "Conviction Score",
        "Rev Growth% (CAGR)",
        "Rev Q1 (1000Cr)", "Rev Q2 (1000Cr)", "Rev Q3 (1000Cr)", "Rev Q4 (1000Cr)",
        "Data Sources",
    ]
    disp_final = disp[[c for c in COLS if c in disp.columns]].copy()

    # ── Top 10 overall ───────────────────────────────────────────────────────
    if not scr.empty:
        with st.expander("Top 10 overall (across all sectors)", expanded=False):
            top10 = scr.nlargest(10, "Score").copy()
            top10_cols = ["Ticker", "Sector", "Score", "Conviction Score",
                          "Quality Score", "Momentum Score",
                          "P/E", "PEG", "Earn Traj"]
            top10_cols = [c for c in top10_cols if c in top10.columns]
            for c in top10_cols:
                if c not in ("Ticker", "Sector"):
                    top10[c] = safe_round(top10[c], 2)
            st.dataframe(top10[top10_cols], use_container_width=True, height=380)

    # ── Sector distribution ──────────────────────────────────────────────────
    if not filt.empty:
        with st.expander("Sector distribution", expanded=False):
            sector_df = (filt.groupby("Sector")
                              .agg(Count=("Ticker", "count"),
                                   MC_Sum=("Mkt Cap (LCr)", "sum"))
                              .reset_index())
            total_mc = filt["Mkt Cap (LCr)"].sum()
            sector_df["MC%"] = (sector_df["MC_Sum"] / total_mc * 100.0).round(2)
            sector_df = sector_df.sort_values("Count", ascending=False)

            x_sort = alt.EncodingSortField(field="Count", op="sum", order="descending")
            bar = (alt.Chart(sector_df)
                      .mark_bar(color="#3b82f6")
                      .encode(x=alt.X("Sector:N", sort=x_sort,
                                        axis=alt.Axis(labelAngle=-45)),
                              y=alt.Y("Count:Q", title="Number of stocks")))
            line = (alt.Chart(sector_df)
                       .mark_line(color="#f97316", point=alt.OverlayMarkDef(color="#f97316"))
                       .encode(x=alt.X("Sector:N", sort=x_sort,
                                        axis=alt.Axis(labelAngle=-45)),
                               y=alt.Y("MC%:Q", title="% of total market cap")))
            chart = (alt.layer(bar, line)
                          .resolve_scale(y="independent")
                          .properties(height=320))
            st.altair_chart(chart, use_container_width=True)

    # ── Main table ───────────────────────────────────────────────────────────
    fmt_cols = [c for c in disp_final.columns
                if c not in ("Ticker", "Sector", "Quality Flag", "PEG Method", "Data Sources")]
    styled = disp_final.style.format("{:.2f}", subset=fmt_cols, na_rep="")

    green_cols = [c for c in disp_final.columns if METRIC_DIRECTION.get(c) == "green"]
    red_cols = [c for c in disp_final.columns if METRIC_DIRECTION.get(c) == "red"]
    if green_cols:
        styled = styled.apply(_green_grad, axis=0, subset=green_cols)
    if red_cols:
        styled = styled.apply(_red_grad, axis=0, subset=red_cols)
    st.dataframe(styled, use_container_width=True, height=680)

    st.download_button(
        label="Download CSV",
        data=disp_final.to_csv(index=False).encode("utf-8"),
        file_name=f"{csv_prefix}_{datetime.now().strftime('%Y%m%d_%H%M')}.csv",
        mime="text/csv",
        key=f"{key_prefix}_download",
    )


# ═══════════════════════════════════════════════════════════════════════════════
# ML Insights page
# ═══════════════════════════════════════════════════════════════════════════════
def _load_ml_metrics():
    path = DATA_DIR / "evaluation" / "ml_metrics.json"
    if not path.exists():
        return {}
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def _load_ml_predictions(horizon: str):
    path = DATA_DIR / "evaluation" / f"ml_predictions_{horizon}.parquet"
    if not path.exists():
        return pd.DataFrame()
    return pd.read_parquet(path)


def _safe_pct(val):
    return f"{val:.3f}" if isinstance(val, (int, float)) and not pd.isna(val) else "—"


def render_ml_page():
    st.markdown("### ML Insights")
    st.caption(
        "XGBoost models trained on historical snapshots to predict forward returns. "
        "Results appear automatically once the scheduled workflow has accumulated enough price history."
    )

    metrics = _load_ml_metrics()
    if not metrics:
        st.info(
            "No ML outputs found yet. The first model(s) will be generated after a few scheduled runs "
            "have built up a small price-history archive."
        )
        return

    horizon = st.selectbox("Prediction horizon", list(metrics.keys()), key="ml_horizon")
    m = metrics.get(horizon, {})

    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Model IC", _safe_pct(m.get("test_ic")))
    c2.metric("Score IC", _safe_pct(m.get("score_ic")))
    c3.metric("Top-Bottom Q Spread", _safe_pct(m.get("top_bottom_quintile_spread")))
    c4.metric("Top-20 Active Return", _safe_pct(m.get("top20_mean_active_return")))
    c5.metric("Active Sharpe", _safe_pct(m.get("top20_active_sharpe")))

    fi = pd.DataFrame(m.get("feature_importance", []))
    if not fi.empty:
        st.markdown("#### Top model features")
        fi = fi.sort_values("importance", ascending=True).tail(15)
        chart = (
            alt.Chart(fi)
            .mark_bar()
            .encode(
                x=alt.X("importance:Q", title="Importance"),
                y=alt.Y("feature:N", sort="-x", title=None),
                color=alt.value("#3b82f6"),
            )
            .properties(height=320)
        )
        st.altair_chart(chart, use_container_width=True)

    preds = _load_ml_predictions(horizon)
    if not preds.empty:
        latest_date = preds["run_date"].max()
        latest = (
            preds[preds["run_date"] == latest_date]
            .sort_values("predicted_return", ascending=False)
            .head(20)
            .copy()
        )
        latest["predicted_return"] = pd.to_numeric(latest["predicted_return"], errors="coerce").round(4)
        latest["actual_return"] = pd.to_numeric(latest["actual_return"], errors="coerce").round(4)
        if "nifty50_return" in latest.columns:
            latest["nifty50_return"] = pd.to_numeric(latest["nifty50_return"], errors="coerce").round(4)
        st.markdown(f"#### Top 20 predicted stocks (latest run: {latest_date})")
        display_cols = [c for c in ["Ticker", "Sector", "Score", "predicted_return", "actual_return", "nifty50_return"] if c in latest.columns]
        st.dataframe(latest[display_cols], use_container_width=True, height=420)

    port_path = DATA_DIR / "evaluation" / f"ml_portfolio_{horizon}.csv"
    if port_path.exists():
        port = pd.read_csv(port_path)
        if not port.empty and {"cum_portfolio", "cum_benchmark", "cum_active"}.issubset(port.columns):
            st.markdown("#### Cumulative backtest returns")
            df = port[["run_date", "cum_portfolio", "cum_benchmark", "cum_active"]].melt("run_date")
            chart = (
                alt.Chart(df)
                .mark_line()
                .encode(
                    x=alt.X("run_date:T", title="Date"),
                    y=alt.Y("value:Q", title="Cumulative return (1 = start)"),
                    color=alt.Color("variable:N", title="Portfolio"),
                )
                .properties(height=320)
            )
            st.altair_chart(chart, use_container_width=True)


# ═══════════════════════════════════════════════════════════════════════════════
# App entry point
# ═══════════════════════════════════════════════════════════════════════════════
st.set_page_config(
    page_title="Indian Stock Screener",
    layout="wide",
    page_icon="🇮🇳",
)

scr50 = _load_snapshot("latest_screener_nifty50.parquet")
scr500 = _load_snapshot("latest_screener_nifty500.parquet")

st.markdown(
    "<style>"
    "div[data-testid='stDataFrame'] table{font-size:13px;}"
    ".stDataFrame thead th{background:#1a1a2e;color:#93c5fd;font-weight:700;}"
    "</style>",
    unsafe_allow_html=True,
)
st.markdown("## 🇮🇳 Indian Stock Screener")
st.caption(
    f"Snapshot dashboard · loads instantly from saved data · "
    f"last updated: {_latest_update_text()}"
)

if scr50.empty and scr500.empty:
    st.info("No snapshot found. Run `python update_data.py` first or wait for the GitHub Action.")
    st.stop()

_sel_col, _refresh_col = st.columns([5, 1])
with _sel_col:
    _selected_page = st.segmented_control(
        "View", ["Nifty 50", "Nifty 500", "ML Insights", "Reference Sheet"],
        default="Nifty 50", label_visibility="collapsed"
    )
with _refresh_col:
    if st.button("Refresh", key="refresh_main"):
        st.cache_data.clear()
        st.rerun()

if _selected_page == "Reference Sheet":
    render_reference_guide()
    st.stop()

if _selected_page == "ML Insights":
    render_ml_page()
    st.stop()

scr = scr50 if _selected_page == "Nifty 50" else scr500
csv_prefix = "nifty50_screener" if _selected_page == "Nifty 50" else "nifty500_screener"
_render_screener_page(scr, _selected_page, csv_prefix)
