# app.py
"""Fast snapshot dashboard for the Indian screener.

Loads pre-built Nifty 50 / Nifty 500 snapshots generated by update_data.py.
"""

from pathlib import Path

import pandas as pd
import streamlit as st

from screener_app_legacy import render_screener_ui, render_reference_guide


DATA_DIR = Path(__file__).parent / "data"


@st.cache_data(ttl=300)
def _load_snapshot(name: str) -> pd.DataFrame:
    path = DATA_DIR / name
    if not path.exists():
        return pd.DataFrame()
    df = pd.read_parquet(path)
    for col in df.columns:
        if df[col].dtype.name == "object":
            df[col] = df[col].infer_objects()
    return df


def _latest_update_text() -> str:
    path = DATA_DIR / "last_update.json"
    if not path.exists():
        return "unknown"
    try:
        from datetime import datetime
        dt = datetime.fromisoformat(path.read_text().strip())
        return dt.strftime("%Y-%m-%d %H:%M UTC")
    except Exception:
        return "unknown"


st.set_page_config(
    page_title="Indian Stock Screener",
    layout="wide",
    page_icon="🇮🇳",
    initial_sidebar_state="collapsed",
)

st.markdown("## 🇮🇳 Indian Stock Screener")
st.caption(
    f"Snapshot dashboard · loads instantly from saved data · "
    f"last updated: {_latest_update_text()}"
)

scr50 = _load_snapshot("latest_screener_nifty50.parquet")
scr500 = _load_snapshot("latest_screener_nifty500.parquet")

if scr50.empty and scr500.empty:
    st.error("No snapshot found. Run update_data.py first or wait for the GitHub Action.")
    st.stop()

if st.button("🔄 Refresh snapshot", use_container_width=False):
    st.cache_data.clear()
    st.rerun()

pg1, pg2, pg3 = st.tabs(["Nifty 50", "Nifty 500", "Reference Sheet"])

with pg1:
    if scr50.empty:
        st.warning("Nifty 50 snapshot not available.")
    else:
        render_screener_ui(scr50, "Nifty 50")

with pg2:
    if scr500.empty:
        st.warning("Nifty 500 snapshot not available.")
    else:
        render_screener_ui(scr500, "Nifty 500")

with pg3:
    render_reference_guide()
